server:
  port: 8080
  session:
    name: goMail
    path: ../sessions
    cookie:
      httpOnly: true
      secure: false

db:
  host: localhost
  port: 3306
  user: gomail
  password: gomail
  database: gomail
